# Understand the Basics

## Neural Network Architecture: 
Understand the basic components, such as input layer, hidden layers, output layer, neurons, weights, and biases.
## Activation Functions: 
Learn about functions like Sigmoid, ReLU, and Softmax.
## Loss Functions: 
Understand concepts of loss functions like Mean Squared Error (MSE) or Cross-Entropy.

# Conceptual Outline of a Neural Network Project

## Introduction
- **Objective**: Design and implement a neural network using only NumPy, focusing on the fundamental principles of machine learning and linear algebra.

## 1. Neural Network Architecture
- **Linear Algebra Perspective**: View neurons and layers as vectors and matrices.
- **Layers**: Input, hidden, and output layers, each represented by matrices of weights and bias vectors.
- **Neurons**: Units of computation, aggregating input through matrix operations.

## 2. Mathematical Foundations
- **Matrix Operations**: Emphasize the use of matrix multiplication, addition, and transpose operations in the network's computations.
- **Activation Functions**: Conceptualize as vectorized non-linear transformations (e.g., Sigmoid or ReLU applied element-wise).

## 3. Forward Propagation
- **Linear Transformation**: `Z = W*X + b`, where `W` and `X` are matrices, and `b` is a bias vector.
- **Activation**: Apply an activation function on `Z` to introduce non-linearity.

## 4. Loss Function
- **Theory**: Understand the purpose of a loss function in quantifying prediction error.
- **Implementation**: Use a function like MSE or Cross-Entropy, represented in a linear algebra framework.

## 5. Backward Propagation
- **Gradient Computation**: Utilize the chain rule in a matrix calculus context to compute gradients of the loss with respect to weights and biases.
- **Backpropagation Algorithm**: Conceptually, this is the reverse of forward propagation, applying the chain rule through layers.

## 6. Parameter Update
- **Gradient Descent**: Update the weights and biases by moving in the direction opposite to the gradient.
- **Learning Rate**: Control the step size in the gradient descent.

## 7. Model Integration and Training
- **Epochs**: Iterate over the dataset multiple times.
- **Batch Processing**: Optionally introduce the concept of mini-batch gradient descent.

## 8. Evaluation and Prediction
- **Predictive Function**: Apply the trained model to new data.
- **Performance Metrics**: Evaluate accuracy, precision, recall, etc.

## 9. Experimental Setup
- **Dataset**: Choose an appropriate dataset for testing.
- **Training/Testing Split**: Emphasize the importance of unbiased model evaluation.

## 10. Advanced Topics (Optional)
- **Regularization**: Techniques like L1, L2 regularization to prevent overfitting.
- **Optimization Algorithms**: Beyond basic gradient descent, explore algorithms like Adam, RMSprop.


# Summary: Single Layer Neural Networks from a Statistical Perspective
(based on "Introduction to statistical learning")

## Conceptual Overview
- **Purpose**: A neural network aims to build a nonlinear function `f(X)` to predict the response `Y`, using an input vector of variables `X = (X1, X2, ..., Xp)`.
- **Distinction**: Unlike trees, boosting, and generalized additive models, neural networks have a unique structure characterized by layers and units.

## Neural Network Model
- **Input Layer**: Consists of features `X1, ..., Xp` as units.
- **Hidden Layer**: Each input feeds into `K` hidden units (in this example, `K=5`).
- **Model Representation**:
  $$ f(X) = β0 + ∑_{k=1}^{K} βk g(wk0 + ∑_{j=1}^{p} wkj Xj) $$
- **Activation Functions**: `g(z)` is a nonlinear function. Popular choices are sigmoid and ReLU (Rectified Linear Unit).

## Activation Functions
- **Sigmoid**: 
  $ g(z) = \frac{1}{1 + e^{-z}} $
- **ReLU**:
  $ g(z) = max(0, z) $
- **Efficiency**: ReLU is preferred for its computational efficiency.

## Computation in Hidden Layer
- **Activations**: Calculated as $Ak = hk(X) = g(wk0 + ∑_{j=1}^{p} wkj Xj)$.
- **Role of Activations**: Similar to basis functions, transforming original features.

## Output Layer
- **Formulation**: The output is a linear regression in the activations `Ak`.
- **Parameters**: Includes both weights `w` and biases `β`, to be estimated from data.

## Nonlinearity and Interaction Effects
- Nonlinear activation functions allow the model to capture complex patterns and interactions.
- Example with quadratic `g(z)` illustrates how nonlinear transformations can model interactions.

## Fitting the Neural Network
- **Loss Function**: Typically squared-error loss for quantitative responses.
- **Optimization**: Minimize the sum of squared errors between predictions and actual values.

*This section is based on the paper "The Neural Network, its Techniques and Applications" by Casey Schafer (2016)*

# Basic Neural Network: Perceptron Explanation

A **perceptron** is the most basic form of a neural network. It consists of one layer of inputs and one layer of outputs. Let's break down the components and the operation of this network step by step, exemplifying with :

## Layers and Vectors

1. **Layers**: In a perceptron, layers are visualized as a series of nodes aligned vertically.
   - An **input layer** is represented by a vector for one observation. For example, vector `x` is `[x1 x2]ᵀ`.
   - With multiple observations, each layer is represented as a matrix.

2. **Input Layer (X)**: For a perceptron with two inputs and `p` observations, the input layer is a `2 × p` matrix, denoted as `X`.

3. **Output Layer (Y)**: 
   - The output is represented by the variable `y`.
   - The output matrix `Y` is typically `n × p` but, in this basic case, it simplifies to `1 × p`.
   - `Y` is the predicted output by the network, different from `T`, which is the known output in supervised learning.

## Goal of the Neural Network

- The objective is to minimize the difference between the known output `T` and the predicted output `Y`.
- The ideal network predicts `T` accurately using only the inputs.

## Weight Matrix (W)

- To map from `X` to `Y`, we introduce a weight matrix `W`.
- In general, `W` is an `n × m` matrix, where `m` is the number of input nodes, independent of the number of observations.
- The fundamental equation of the network is: `T = W * X + b`, where `b` is a bias vector.

## Linearization

- To linearize this equation, augment `W` with `b` as `[W | b]` and add a row of 1’s to `X`.
- The equation becomes: `T = [W | b] * [X; 1]`.
- We redefine `W` to be `n × (m + 1)` and `X` to be `(m + 1) × p` with a row of 1’s at the bottom.

## Solving for W

- We don't "solve" this equation in the traditional sense. Instead, we compute the pseudoinverse of `X` to find an approximation of `W`, denoted as `Ŵ`.
- `Ŵ` is calculated as `Ŵ = T * V * Σ⁻¹ * Uᵀ`, where `V`, `Σ`, and `U` are derived from the singular value decomposition of `X`.
- This `Ŵ` is a projection onto the column space of `X`.

## Predicted Output (Y)

- The predicted output `Y` is computed as `Y = Ŵ * X`.
- `Y` equals `T` only if `T` is in the column space of `X`, which is rare.
- Otherwise, `Y` is as close to `T` as possible, given the constraints.

## Limitations and Extensions

- This linear algebra method works best if the relationship between `X` and `T` is linear, which is also rare.
- For more complex relationships, we extend the model to a more sophisticated neural network that can handle non-linear functions.


In [ ]:
import pickle

with open('mini-mnist-1000.pickle', 'rb') as f:
    data = pickle.load(f)

images = data['images'] # a list of 1000 numpy image matrices
labels = data['labels'] # a list of 1000 integer labels

In [7]:
import numpy as np

def initialize_weights(n_inputs, n_outputs):
    """
    Randomly initializes the weight matrix and bias vector.
    """
    W = np.random.randn(n_outputs, n_inputs)
    b = np.random.randn(n_outputs, 1)
    return W, b

def linear_transform(X, W, b):
    """
    Computes the linear transformation W * X + b.
    """
    return np.dot(W, X) + b

def compute_pseudoinverse(X):
    """
    Computes the pseudoinverse of matrix X.
    """
    U, S, VT = np.linalg.svd(X, full_matrices=False)
    S_inv = np.diag(1 / S)
    X_pinv = np.dot(VT.T, np.dot(S_inv, U.T))
    return X_pinv

def train_perceptron(X, T):
    """
    Trains the perceptron using pseudoinverse to find the optimal weights.
    """
    X_pinv = compute_pseudoinverse(X)
    W_hat = np.dot(T, X_pinv)
    return W_hat

def predict(X, W):
    """
    Uses the trained perceptron to predict outputs.
    """
    return np.dot(W, X)

# Example usage
n_inputs = 4  # Number of input nodes
n_outputs = 1 # Number of output nodes
p = 5         # Number of observations

# Random example data
X = np.random.randn(n_inputs, p)  # Input data
T = np.random.randn(n_outputs, p) # Target output

print("X shape:", X.shape)
print("T shape:", T.shape)
print("X:", X)
print("T:", T)

# Training the perceptron
W_hat = train_perceptron(X, T)
print("W_hat shape:", W_hat.shape)
print("W_hat:", W_hat)

# Predicting new inputs
new_X = np.random.randn(n_inputs, p)

print("New X shape:", new_X.shape)
print("New X:", new_X)


predictions = predict(new_X, W_hat)

print("Predictions:", predictions)


X shape: (4, 5)
T shape: (1, 5)
X: [[-0.82564301  0.78477748  0.31311514 -1.0836756  -2.19473362]
 [ 0.71074089 -0.76406765  0.32480617  1.88997109  1.19662102]
 [ 1.40289635  0.85435855  0.64118954 -0.08368818 -0.92360596]
 [-0.43496685 -1.83350986  0.0928096  -1.55390604 -0.69541564]]
T: [[-0.31068405 -1.01206771  0.72946336  0.8478648  -0.3655965 ]]
W_hat shape: (1, 4)
W_hat: [[ 0.84864578  1.22048007 -0.20432708  0.32805125]]
New X shape: (4, 5)
New X: [[-0.62371697  0.02019627 -0.26861686 -0.38929488  1.33407436]
 [ 1.29733104  0.29565742  0.25977682 -0.95211057  0.66521986]
 [-0.01698883 -1.25691953 -0.97536636  0.26575612 -0.84163206]
 [-0.78828163  0.39129256 -0.03291746  0.02240144 -0.40793631]]
Predictions: [[ 0.7989264   0.76317017  0.27758701 -1.53935778  1.98218836]]
